### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by neclitoris** [atar-axis/xpadneo#150]
**Describe the bug**
When running `sudo ./install.sh`, an error happens.
```
* replacing version string if necessary
* copying module into /usr/src
* adding module to DKMS

Creating symlink /var/lib/dkms/hid-xpadneo/0.6.0/source ->
                 /usr/src/hid-xpadneo-0.6.0

DKMS: add completed.
* installing module (using DKMS)

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.0.0-37-generic -C /lib/modules/5.0.0-37-generic/build M=/var/lib/dkms/hid-xpadneo/0.6.0/build/src modules...(bad exit status: 2)
ERROR (dkms apport): binary package for hid-xpadneo: 0.6.0 not found
Error! Bad return status for module build on kernel: 5.0.0-37-generic (x86_64)
Consult /var/lib/dkms/hid-xpadneo/0.6.0/build/make.log for more information.
```

`/var/lib/dkms/hid-xpadneo/0.6.0/build/make.log` says the following:
```
DKMS make.log for hid-xpadneo-0.6.0 for kernel 5.0.0-37-generic (x86_64)
Fri Dec 20 19:55:18 MSK 2019
make: Entering directory '/usr/src/linux-headers-5.0.0-37-generic'
  CC [M]  /var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o
/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.c: In function ‘xpadneo_ff_play’:
/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.c:85:4: error: implicit declaration of function ‘hid_printk’; did you mean ‘dev_printk’? [-Werror=implicit-function-declaration]
    hid_printk(KERN_DEBUG, pr_fmt(fmt_hdev), \
    ^
/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.c:268:2: note: in expansion of macro ‘hid_dbg_lvl’
  hid_dbg_lvl(DBG_LVL_FEW, hdev, "playing effect: strong: %#04x, weak: %#04x, direction: %#04x\n",
  ^~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:291: recipe for target '/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o' failed
make[1]: *** [/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o] Error 1
Makefile:1614: recipe for target '_module_/var/lib/dkms/hid-xpadneo/0.6.0/build/src' failed
make: *** [_module_/var/lib/dkms/hid-xpadneo/0.6.0/build/src] Error 2
make: Leaving directory '/usr/src/linux-headers-5.0.0-37-generic'
```

After kernel update it module also breaks.

**To Reproduce**
1. clone repository (or pull latest version)
2. run `sudo ./install.sh`

or

1. get a kernel update

**Expected behavior**
Successful build/no module break on kernel update

**System information**
```bash
$ uname -a
Linux neclitoris 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Other outputs don't seem useful here

**Additional context**  
It seems like `hid_printk` macro was removed in some recent kernel version. Replacing it with `hid_dbg` should help.

**Comment by neclitoris** [comment]
My bad. Was sure that I had latest version. It's fixed already. Apologies.
