### ISSUE TITLE
"Unsupported AUTOINSTALL value 'Y' in dkms.conf" and uninstall.sh not removed module on Debian Linux

### ISSUE THREAD

**Issue by slrslr** [atar-axis/xpadneo#555]
On Debian 12 after upgrading packages to Trixie (Debian 13) I have then seen a problem during "apt" run.

Files:
/home/myuser/myapps/xpadneo/hid-xpadneo/dkms.conf
/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/source/dkms.conf

(old/outdated version!!)

contained line: AUTOINSTALL="Y"
while it [should be AUTOINSTALL="yes"](https://manpages.debian.org/trixie/dkms/dkms.8.en.html#AUTOINSTALL=)

and the kernel modules installation (part of apt upgrade) has been failing:

```
Setting up linux-image-6.12.41+deb13-amd64 (6.12.41-1) ...
/etc/kernel/postinst.d/dkms:
dkms.conf: Error! Unsupported AUTOINSTALL value 'Y'

Error! Bad conf file.
File: /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/source/dkms.conf does not represent a valid dkms.conf file.
run-parts: /etc/kernel/postinst.d/dkms exited with return code 1
dpkg: error processing package linux-image-6.12.41+deb13-amd64 (--configure):
 installed linux-image-6.12.41+deb13-amd64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-image-amd64:
 linux-image-amd64 depends on linux-image-6.12.41+deb13-amd64 (= 6.12.41-1); however:
  Package linux-image-6.12.41+deb13-amd64 is not configured yet.

dpkg: error processing package linux-image-amd64 (--configure):
 dependency problems - leaving unconfigured
```

After doing replacement of that AUTOINSTALL value and re-running apt command:
```
Autoinstall of module hid-xpadneo/v0.9-102-ga279cc4 for kernel 6.12.41+deb13-amd64 (x86_64)
Building module(s)...(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.12.41+deb13-amd64 -C /lib/modules/6.12.41+deb13-amd64/build M=/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src VERSION=v0.9-102-ga279cc4 modules

Error! Bad return status for module build on kernel: 6.12.41+deb13-amd64 (x86_64)
Consult /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/make.log for more information.
```

log file:

```
DKMS (dkms-3.2.0) make.log for hid-xpadneo/v0.9-102-ga279cc4 for kernel 6.12.41+deb13-amd64 (x86_64)
Fri Aug 15 12:13:00 PM CEST 2025

Building module(s)
# command: make -j16 KERNELRELEASE=6.12.41+deb13-amd64 -C /lib/modules/6.12.41+deb13-amd64/build M=/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src VERSION=v0.9-102-ga279cc4 modules
make: Entering directory '/usr/src/linux-headers-6.12.41+deb13-amd64'
cp /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/hid-xpadneo.c /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo.c
  CC [M]  /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo/core.o
  CC [M]  /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo/consumer.o
  CC [M]  /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo.o
/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo.c:1321:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘u8 * (*)(struct hid_device *, u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
 1321 |         .report_fixup = xpadneo_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo.c:1321:25: note: (near initialization for ‘xpadneo_driver.report_fixup’)
make[2]: *** [/usr/src/linux-headers-6.12.41+deb13-common/scripts/Makefile.build:234: /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src/xpadneo.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.12.41+deb13-common/Makefile:1970: /var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/build/src] Error 2
make: *** [/usr/src/linux-headers-6.12.41+deb13-common/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.41+deb13-amd64'

# exit code: 2
# elapsed time: 00:00:01
```

After going to /home/myuser/myapps/xpadneo/ and running "git pull" and then "sudo ./install.sh":

```
Installing /lib/modules/6.1.0-37-amd64/updates/dkms/hid-xpadneo.ko
...
unning depmod.... done.
dkms.conf: Error! Unsupported AUTOINSTALL value 'Y'

Error! Bad conf file.
File:  does not represent a valid dkms.conf file.
```

$ grep AUTO ./hid-xpadneo/dkms.conf
`AUTOINSTALL="yes"`

$ grep AUTO /var/lib/dkms/hid-xpadneo/*/source/dkms.conf
```
/var/lib/dkms/hid-xpadneo/v0.9-102-ga279cc4/source/dkms.conf:AUTOINSTALL="Y"
/var/lib/dkms/hid-xpadneo/v0.9-226-ga16acb0/source/dkms.conf:AUTOINSTALL="yes"
```

the (un)install.sh scripts has been a bit problematic (uninstall not removed the module) as per [this output](https://bin.disroot.org/?18194339cfca368b#51Hkj8dtFN1Km1aFXGq2eMC1Ngumj2XNaXpTqSexjRaF).

Please see if anything can be improved.

**Comment by kakra** [comment]
Duplicate of https://github.com/atar-axis/xpadneo/issues/431

**Comment by kakra** [comment]
> the (un)install.sh scripts has been a bit problematic (uninstall not removed the module) as per [this output](https://bin.disroot.org/?18194339cfca368b#51Hkj8dtFN1Km1aFXGq2eMC1Ngumj2XNaXpTqSexjRaF).
> 
> Please see if anything can be improved.

According to the log, the uninstaller removed an older version while a newer was already present. We cannot automatically clean that up. You need to fix this manually by purging the orphan directories from dkms.

The new make-based installer may work better for that situation.
