### ISSUE TITLE
Build issue on kernel 6.17.0+

### ISSUE THREAD

**Issue by rkn45** [atar-axis/xpadneo#562]
## Version of xpadneo

Clone of the master branch, dkms reports it as v0.9-144-g9b3b696

## Severity / Impact

- [x] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] I've tried disabling or running without above mentioned software
- [x] It does not work at all
- [x] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug

Build fails on mainline kernel 6.17.0+ 

```
Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.17.0+ -C /lib/modules/6.17.0+/build M=/var/lib/dkms/hid-xpadneo/v0.9-144-g9b3b696/build/src VERSION=v0.9-144-g9b3b696 modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.17.0+ (x86_64)
Consult /var/lib/dkms/hid-xpadneo/v0.9-144-g9b3b696/build/make.log for more information.
```

## Steps to Reproduce

Just build the module, either with DKMS or by running install.sh

## Expected Behavior

The module should build without errors.

## Additional Context

Below is full make.log of the failed build:
```
DKMS make.log for hid-xpadneo-v0.9-144-g9b3b696 for kernel 6.17.0+ (x86_64)
Sat Oct 11 13:55:25 MSK 2025
make: Entering directory '/usr/src/linux-headers-6.17.0+'
make[1]: Entering directory '/var/lib/dkms/hid-xpadneo/v0.9-144-g9b3b696/build/src'
cp hid-xpadneo.c xpadneo.c
  CC [M]  xpadneo/core.o
  CC [M]  xpadneo/consumer.o
  CC [M]  xpadneo/keyboard.o
  CC [M]  xpadneo.o
xpadneo.c: In function 'xpadneo_probe':
xpadneo.c:1226:21: error: implicit declaration of function 'ida_simple_get' [-Werror=implicit-function-declaration]
 1226 |         xdata->id = ida_simple_get(&xpadneo_device_id_allocator, 0, 0, GFP_KERNEL);
      |                     ^~~~~~~~~~~~~~
xpadneo.c: In function 'xpadneo_release_device_id':
xpadneo.c:1331:17: error: implicit declaration of function 'ida_simple_remove' [-Werror=implicit-function-declaration]
 1331 |                 ida_simple_remove(&xpadneo_device_id_allocator, xdata->id);
      |                 ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.17.0+/scripts/Makefile.build:287: xpadneo.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.17.0+/Makefile:2010: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.17.0+/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/hid-xpadneo/v0.9-144-g9b3b696/build/src'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.17.0+'
```

**Comment by kode54** [comment]
The "6.17+" they claim to be using appears to be based on 6.18. I also see the same two symbols fail when attempting to install on a 6.18-rc1 kernel.

**Comment by kakra** [comment]
We need to fix this when 6.18 settles.
